type Recharge {
  _id: ID!
  rechargeStartTime: String!
  rechargeEndTime: String!
  station: Station!
  user: User!
}

input RechargeInput {
  rechargeValue: Int!
  rechargeEndTime: String!
  stationId: ID!
  userId: ID!
}

type Query {
  recharges: [Recharge]!
}

type Mutation {
  recharge(rechargeData: RechargeInput!): Recharge!
}