type User {
  _id: ID!
  name: String!
  email: String
  password: String
}

input UserInput {
  name: String!
  email: String!
  password: String!
}

type Query {
  user(id: ID!): User!
  users: [User]!
}

type Mutation {
  createUser(userData: UserInput!): User!
}