type Station {
  _id: ID!
  exoplanet: String!
  fuel: Int!
}

input StationInput {
  planetName: String!
  fuelStation: Int!
}

type Query {
  stations: [Station]!
}

type Mutation {
  installStation(stationData: StationInput!): Station!
}