type Exoplanet {
  pl_name: String
  pl_letter: String
  hostname: String
  hd_name: String
  hip_name: String
  tic_id: String
  gaia_id: String
  default_flag: Int
  pl_refname: String
  sy_refname: String
  disc_pubdate: String
  disc_year: Int
  discoverymethod: String
  disc_locale: String
  disc_facility: String
  disc_instrument: String
  disc_telescope: String
  disc_refname: String
  ra: Float
  rastr: String
  dec: Float
  decstr: String
  glon: Float
  glat: Float
  elon: Float
  elat: Float
  pl_orbper: Float
  pl_orbpererr1: Float
  pl_orbpererr2: Float
  pl_orbperlim: Float
  pl_orbperstr: String
  pl_orblpererr1: Float
  pl_orblper: Float
  pl_orblpererr2: Float
  pl_orblperlim: Float
  pl_orblperstr: String
  pl_orbsmax: Float
  pl_orbsmaxerr1: Float
  pl_orbsmaxerr2: Float
  pl_orbsmaxlim: Int
  pl_orbsmaxstr: String
  pl_orbincl: Float
  pl_orbinclerr1: Float
  pl_orbinclerr2: Float
  pl_orbincllim: Float
  pl_orbinclstr: String
  pl_orbtper: Float
  pl_orbtpererr1: Float
  pl_orbtpererr2: Float
  pl_orbtperlim: Float
  pl_orbtperstr: String
  pl_orbeccen: Float
  pl_orbeccenerr1: Float
  pl_orbeccenerr2: Float
  pl_orbeccenlim: Float
  pl_orbeccenstr: String
  pl_eqt: Float
  pl_eqterr1: Float
  pl_eqterr2: Float
  pl_eqtlim: Float
  pl_eqtstr: String
  pl_occdep: Float
  pl_occdeperr1: Float
  pl_occdeperr2: Float
  pl_occdeplim: Float
  pl_occdepstr: String
  pl_insol: Float
  pl_insolerr1: Float
  pl_insolerr2: Float
  pl_insollim: Float
  pl_insolstr: String
  pl_dens: Float
  pl_denserr1: Float
  pl_denserr2: Float
  pl_denslim: Float
  pl_densstr: String
  pl_trandep: Float
  pl_trandeperr1: Float
  pl_trandeperr2: Float
  pl_trandeplim: Float
  pl_trandepstr: String
  pl_tranmid: Float
  pl_tranmiderr1: Float
  pl_tranmiderr2: Float
  pl_tranmidlim: Float
  pl_tranmidstr: String
  pl_trandur: Float
  pl_trandurerr1: Float
  pl_trandurerr2: Float
  pl_trandurlim: Float
  pl_trandurstr: String
  sy_kmagstr: String
  sy_umag: Float
  sy_umagerr1: Float
  sy_umagerr2: Float
  sy_umagstr: String
  sy_rmag: Float
  sy_rmagerr1: Float
  sy_rmagerr2: Float
  sy_rmagstr: String
  sy_imag: Float
  sy_imagerr1: Float
  sy_imagerr2: Float
  sy_imagstr: String
  sy_zmag: Float
  sy_zmagerr1: Float
  sy_zmagerr2: Float
  sy_zmagstr: String
  sy_w1mag: Int
  sy_w1magerr1: Int
  sy_w1magerr2: Int
  sy_w1magstr: String
  sy_w2mag: Int
  sy_w2magerr1: Int
  sy_w2magerr2: Int
  sy_w2magstr: String
  sy_w3mag: Int
  sy_w3magerr1: Int
  sy_w3magerr2: Int
  sy_w3magstr: String
  sy_w4mag: Int
  sy_w4magerr1: Float
  sy_w4magerr2: Float
  sy_w4magstr: String
  sy_gmag: Float
  sy_gmagerr1: Float
  sy_gmagerr2: Float
  sy_gmagstr: String
  sy_gaiamag: Int
  sy_gaiamagerr1: Int
  sy_gaiamagerr2: Int
  sy_gaiamagstr: String
  sy_tmag: Int
  sy_tmagerr1: Int
  sy_tmagerr2: Int
  sy_tmagstr: String
  pl_controv_flag: Int
  pl_tsystemref: Float
  st_metratio: Float
  st_spectype: String
  sy_kepmag: Float
  sy_kepmagerr1: Float
  sy_kepmagerr2: Float
  sy_kepmagstr: String
  st_rotp: Float
  st_rotperr1: Float
  st_rotperr2: Float
  st_rotplim: Float
  st_rotpstr: String
  pl_projobliq: Float
  pl_projobliqerr1: Float
  pl_projobliqerr2: Float
  pl_projobliqlim: Float
  pl_projobliqstr: String
  x: Float
  y: Float
  z: Float
  htm20: Int
  pl_rvamp: Float
  pl_rvamperr1: Float
  pl_rvamperr2: Float
  pl_rvamplim: Float
  pl_rvampstr: String
  pl_radj: Float
  pl_radjerr1: Float
  pl_radjerr2: Float
  pl_radjlim: Float
  pl_radjstr: String
  pl_rade: Float
  pl_radeerr1: Float
  pl_radeerr2: Float
  pl_radelim: Float
  pl_radestr: String
  pl_ratror: Float
  pl_ratrorerr1: Float
  pl_ratrorerr2: Float
  pl_ratrorlim: Float
  pl_ratrorstr: String
  pl_ratdor: Float
  pl_trueobliq: Float
  pl_trueobliqerr1: Float
  pl_trueobliqerr2: Float
  pl_trueobliqlim: Float
  pl_trueobliqstr: String
  sy_icmag: Float
  sy_icmagerr1: Float
  sy_icmagerr2: Float
  sy_icmagstr: String
  rowupdate: String
  pl_pubdate: String
  st_refname: String
  releasedate: String
  dkin_flag: Int
  pl_ratdorerr1: Float
  pl_ratdorerr2: Float
  pl_ratdorlim: Float
  pl_ratdorstr: String
  pl_imppar: Float
  pl_impparerr1: Float
  pl_impparerr2: Float
  pl_impparlim: Float
  pl_impparstr: String
  pl_cmassj: Float
  pl_cmassjerr1: Float
  pl_cmassjerr2: Float
  pl_cmassjlim: Float
  pl_cmassjstr: String
  pl_cmasse: Float
  pl_cmasseerr1: Float
  pl_cmasseerr2: Float
  pl_cmasselim: Float
  pl_cmassestr: String
  pl_massj: Float
  pl_massjerr1: Int
  pl_massjerr2: Int
  pl_massjlim: Int
  pl_massjstr: String
  pl_masse: Int
  pl_masseerr1: Int
  pl_masseerr2: Int
  pl_masselim: Int
  pl_massestr: String
  pl_bmassj: Float
  pl_bmassjerr1: Float
  pl_bmassjerr2: Float
  pl_bmassjlim: Float
  pl_bmassjstr: String
  pl_bmasse: Float
  pl_bmasseerr1: Float
  pl_bmasseerr2: Float
  pl_bmasselim: Float
  pl_bmassestr: String
  pl_bmassprov: String
  pl_msinij: Float
  pl_msinijerr1: Float
  pl_msinijerr2: Float
  pl_msinijlim: Float
  pl_msinijstr: String
  pl_msinie: Float
  pl_msinieerr1: Float
  pl_msinieerr2: Float
  pl_msinielim: Float
  pl_msiniestr: String
  st_teff: Float
  st_tefferr1: Float
  st_tefferr2: Float
  st_tefflim: Float
  st_teffstr: String
  st_met: Float
  st_meterr1: Float
  st_meterr2: Float
  st_metlim: Float
  st_metstr: String
  st_radv: Float
  st_radverr1: Float
  st_radverr2: Float
  st_radvlim: Float
  st_radvstr: String
  st_vsin: Float
  st_vsinerr1: Float
  st_vsinerr2: Float
  st_vsinlim: Float
  st_vsinstr: String
  st_lum: Float
  st_lumerr1: Float
  st_lumerr2: Float
  st_lumlim: Float
  st_lumstr: String
  st_logg: Float
  st_loggerr1: Float
  st_loggerr2: Float
  st_logglim: Float
  st_loggstr: String
  st_age: Int
  st_ageerr1: Float
  st_ageerr2: Float
  st_agelim: Int
  st_agestr: String
  st_mass: Int
  st_masserr1: Float
  st_masserr2: Float
  st_masslim: Int
  st_massstr: String
  st_dens: Float
  st_denserr1: Float
  st_denserr2: Float
  st_denslim: Float
  st_densstr: String
  st_rad: Float
  st_raderr1: Float
  st_raderr2: Float
  st_radlim: Float
  st_radstr: String
  ttv_flag: Int
  ptv_flag: Int
  tran_flag: Int
  rv_flag: Int
  ast_flag: Int
  obm_flag: Int
  micro_flag: Int
  etv_flag: Int
  ima_flag: Int
  pul_flag: Int
  soltype: String
  sy_snum: Int
  sy_pnum: Int
  sy_mnum: Int
  cb_flag: Int
  st_nphot: Int
  st_nrvc: Int
  st_nspec: Int
  pl_nespec: Int
  pl_ntranspec: Int
  pl_nnotes: Int
  sy_pm: Int
  sy_pmerr1: Int
  sy_pmerr2: Int
  sy_pmstr: String
  sy_pmra: Int
  sy_pmraerr1: Int
  sy_pmraerr2: Int
  sy_pmrastr: String
  sy_pmdec: Int
  sy_pmdecerr1: Int
  sy_pmdecerr2: Int
  sy_pmdecstr: String
  sy_plx: Int
  sy_plxerr1: Int
  sy_plxerr2: Int
  sy_plxstr: String
  sy_dist: Int
  sy_disterr1: Int
  sy_disterr2: Int
  sy_diststr: String
  sy_bmag: Float
  sy_bmagerr1: Float
  sy_bmagerr2: Float
  sy_bmagstr: String
  sy_vmag: Float
  sy_vmagerr1: Float
  sy_vmagerr2: Float
  sy_vmagstr: String
  sy_jmag: Int
  sy_jmagerr1: Int
  sy_jmagerr2: Int
  sy_jmagstr: String
  sy_hmag: Int
  sy_hmagerr1: Int
  sy_hmagerr2: Int
  sy_hmagstr: String
  sy_kmag: Int
  sy_kmagerr1: Int
  sy_kmagerr2: Int
}

type Query {
  suitablePlanets(select: String): [Exoplanet]!
}